/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vvote_verifierlibrary_utils_crypto_CryptoUtils */

#ifndef _Included_com_vvote_verifierlibrary_utils_crypto_CryptoUtils
#define _Included_com_vvote_verifierlibrary_utils_crypto_CryptoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vvote_verifierlibrary_utils_crypto_CryptoUtils
 * Method:    openSSLVerifyHashCommitment
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vvote_verifierlibrary_utils_crypto_CryptoUtils_openSSLVerifyHashCommitment
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
